### ISSUE TITLE
Bazarr does not work with default template

### ISSUE THREAD

**Issue by fengcda** [sebgl/htpc-download-box#67]
I needed to remove 

```
    ports:
      - 6767:6767
```

from my docker-compose file and localhost:6767 still worked so I assume it's not necessary.

```
ERROR: for bazarr  "host" network_mode is incompatible with port_bindings

ERROR: for bazarr  "host" network_mode is incompatible with port_bindings
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 202, in perform_command
  File "compose/metrics/decorator.py", line 18, in wrapper
  File "compose/cli/main.py", line 1188, in up
  File "compose/cli/main.py", line 1184, in up
  File "compose/project.py", line 713, in up
  File "compose/parallel.py", line 108, in parallel_execute
  File "compose/parallel.py", line 206, in producer
  File "compose/project.py", line 699, in do
  File "compose/service.py", line 600, in execute_convergence_plan
  File "compose/service.py", line 522, in _execute_convergence_recreate
  File "compose/parallel.py", line 108, in parallel_execute
  File "compose/parallel.py", line 206, in producer
  File "compose/service.py", line 515, in recreate
  File "compose/service.py", line 634, in recreate_container
  File "compose/service.py", line 335, in create_container
  File "compose/service.py", line 959, in _get_container_create_options
  File "compose/service.py", line 1091, in _get_container_host_config
  File "docker/api/container.py", line 598, in create_host_config
  File "docker/types/containers.py", line 339, in __init__
docker.errors.InvalidArgument: "host" network_mode is incompatible with port_bindings
[451362] Failed to execute script docker-compose
```

**Comment by afloresescarcega** [comment]
Was able to replicate and solve this with the suggestion above. Thanks!
